server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always

rocksdb:
  name: "test"
  dir: "test"

kafka:
  bootstrap.servers: "localhost:29092"
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12
  topics:
    consumer-monitor-rate: 1000
    partitions-per-thread: 2
    polling-timeout: 10000
    operation-log-name: "operation_log"


retry:
  max.attempts: 10
  backoff.interval: 1000

scheduled:
  pool:
    size: 10

info:
  version: '@project.version@'
  stage: dev
