server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always
  endpoints:
    web:
      exposure:
        include: info

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always

rocksdb:
  name: "test"
  dir: "src/test/resources/rocksdb-temp"

kafka:
  bootstrap-servers: "localhost:29092"
  ssl:
    enabled: false
  topics:
    consumer-monitor-rate: 1000
    partitions-per-thread: 2
    polling-timeout: 10000
    operation-log-name: "operation_log"


retry:
  max.attempts: 10
  backoff.interval: 1000

scheduled:
  pool:
    size: 10

info:
  version: '@project.version@'
  stage: dev
