server:
  port: @server.port@

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always

kafka:
  bootstrap.servers: "localhost:29092"
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12


retry:
  max.attempts: 10
  backoff.interval: 1000

info:
  version: @project.version@
  stage: dev
